### PR TITLE
First approach to using localstorage

### PR DESCRIPTION
**Pull request by sudodoki**
Just to generate the diff and kick off some questions in [#39], no need to merge this. 

What PR does: 
1. Adds `storage` services, storing messages by room into localstorage (key is `'room:'+id`), with `get, push, unshift, getLast` methods.
2. Uses storage to store data when: 
- fetching data in the addToTop method
- receiving message from the socket
- creating your own room
- Some unit tests just to make sure something works.

### CODE REVIEW

**Comment by edjafarov** [comment]
ping me when done :smile:

**Comment by sudodoki** [comment]
Considering this done, in need of merge.

**Comment by sudodoki** [comment]
Matters that are still to solve:
1. Tests with actual localStorage take a lot of time - phantoms sometimes disconnects on timeout. Ways to solve - mock localstorage / optimize setup for localstorage tests.
2. When the refresh method is called on messages, do we want to cache that too?

**Comment by sudodoki** [comment]
@edjafarov ping :package:

**Comment by sudodoki** [comment]
@edjafarov Yet another ping.

**Comment by edjafarov** [comment]
Looks nice!

**Pull request merged**
